#!/usr/bin/env ruby
# Adds a real iOS Share Extension to the Capacitor iOS project generated by `npx cap add ios`.
# Run from repository root after `npx cap sync ios`.

require 'fileutils'
require 'open3'
require 'xcodeproj'

ROOT = File.expand_path('..', __dir__)
Dir.chdir(ROOT)

APP_BUNDLE_ID = ENV.fetch('BUNDLE_ID', 'com.linkvaultq8.app')
EXTENSION_NAME = ENV.fetch('SHARE_EXTENSION_NAME', 'LinkVaultShareExtension')
EXTENSION_BUNDLE_ID = ENV.fetch('SHARE_EXTENSION_BUNDLE_ID', "#{APP_BUNDLE_ID}.ShareExtension")
APP_GROUP_ID = ENV.fetch('APP_GROUP_ID', 'group.com.linkvaultq8.shared')
USE_APP_GROUPS = ENV.fetch('USE_APP_GROUPS', 'true').downcase == 'true'
DEPLOYMENT_TARGET = ENV.fetch('IOS_DEPLOYMENT_TARGET', '14.0')
PROJECT_PATH = 'ios/App/App.xcodeproj'
APP_INFO_PLIST = 'ios/App/App/Info.plist'
APP_MAIN_STORYBOARD = 'ios/App/App/Base.lproj/Main.storyboard'
APP_BRIDGE_CONTROLLER = 'ios/App/App/LinkVaultBridgeViewController.swift'
EXTENSION_DIR = "ios/App/#{EXTENSION_NAME}"
APP_ENTITLEMENTS = 'ios/App/App/App.entitlements'
EXTENSION_ENTITLEMENTS = "#{EXTENSION_DIR}/#{EXTENSION_NAME}.entitlements"

abort "Missing #{PROJECT_PATH}. Run: npx cap add ios && npx cap sync ios" unless File.exist?(PROJECT_PATH)
abort "Missing #{APP_INFO_PLIST}" unless File.exist?(APP_INFO_PLIST)

FileUtils.mkdir_p(EXTENSION_DIR)
FileUtils.cp('ios-share-extension/Info.plist', "#{EXTENSION_DIR}/Info.plist")
FileUtils.cp('ios-share-extension/ShareViewController.swift', "#{EXTENSION_DIR}/ShareViewController.swift")
FileUtils.cp('ios-share-extension/PendingSharePlugin.swift', 'ios/App/App/PendingSharePlugin.swift')
FileUtils.cp('ios-share-extension/LinkVaultBridgeViewController.swift', APP_BRIDGE_CONTROLLER)


def write_app_group_entitlements(path, app_group_id)
  FileUtils.mkdir_p(File.dirname(path))
  File.write(path, <<~PLIST)
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>com.apple.security.application-groups</key>
      <array>
        <string>#{app_group_id}</string>
      </array>
    </dict>
    </plist>
  PLIST
end

if USE_APP_GROUPS
  write_app_group_entitlements(APP_ENTITLEMENTS, APP_GROUP_ID)
  write_app_group_entitlements(EXTENSION_ENTITLEMENTS, APP_GROUP_ID)
else
  # This Share Extension passes the shared URL to the app through the linkvault:// URL scheme.
  # It does not require App Groups. Keeping App Group entitlements enabled can make archive fail
  # when the App Store provisioning profiles do not contain that capability.
  FileUtils.rm_f(APP_ENTITLEMENTS)
  FileUtils.rm_f(EXTENSION_ENTITLEMENTS)
end

# Add custom URL schemes for share deep links:
# linkvaultq8://share?url=... is the primary scheme, and linkvault:// is kept
# as a legacy fallback for previously installed builds.
def plistbuddy(*args)
  command = ['/usr/libexec/PlistBuddy'] + args + [APP_INFO_PLIST]
  _stdout, _stderr, _status = Open3.capture3(*command)
end
plistbuddy('-c', 'Delete :CFBundleURLTypes')
plistbuddy('-c', 'Add :CFBundleURLTypes array')
plistbuddy('-c', 'Add :CFBundleURLTypes:0 dict')
plistbuddy('-c', "Add :CFBundleURLTypes:0:CFBundleURLName string #{APP_BUNDLE_ID}")
plistbuddy('-c', 'Add :CFBundleURLTypes:0:CFBundleURLSchemes array')
plistbuddy('-c', 'Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string linkvaultq8')
plistbuddy('-c', 'Add :CFBundleURLTypes:0:CFBundleURLSchemes:1 string linkvault')
plistbuddy('-c', 'Delete :LSApplicationQueriesSchemes')
plistbuddy('-c', 'Add :LSApplicationQueriesSchemes array')
plistbuddy('-c', 'Add :LSApplicationQueriesSchemes:0 string linkvaultq8')
plistbuddy('-c', 'Add :LSApplicationQueriesSchemes:1 string linkvault')

# Export compliance: LinkVault only makes standard HTTPS/TLS calls (Supabase,
# its own backend) and implements no custom/proprietary cryptography, so it
# qualifies for Apple's standard exemption. Declaring this in Info.plist
# answers the question at the source so every future automated upload skips
# the "Build is missing export compliance" hold in App Store Connect/TestFlight.
# If LinkVault ever adds its own encryption beyond standard HTTPS, this should
# be revisited rather than left as false.
plistbuddy('-c', 'Delete :ITSAppUsesNonExemptEncryption')
plistbuddy('-c', 'Add :ITSAppUsesNonExemptEncryption bool false')

# Camera access is required only for scanning QR codes inside LinkVault.
plistbuddy('-c', 'Delete :NSCameraUsageDescription')
plistbuddy('-c', 'Add :NSCameraUsageDescription string LinkVault uses the camera to scan QR codes and save links.')


project = Xcodeproj::Project.open(PROJECT_PATH)
app_target = project.targets.find { |t| t.name == 'App' }
abort 'Could not find App target in iOS project' unless app_target

app_group = project.main_group.find_subpath('App', true)
app_group.set_source_tree('<group>')
pending_share_ref = app_group.files.find { |f| File.basename(f.path.to_s) == 'PendingSharePlugin.swift' } || app_group.new_file('PendingSharePlugin.swift')
bridge_controller_ref = app_group.files.find { |f| File.basename(f.path.to_s) == 'LinkVaultBridgeViewController.swift' } || app_group.new_file('LinkVaultBridgeViewController.swift')

# Clean stale/empty extension products left by previous generated scripts.
# Xcode 26 fails archive when an app extension product resolves to `.appex`.
project.targets.each do |target|
  next unless target.respond_to?(:product_type)
  next unless target.product_type == 'com.apple.product-type.app-extension'
  next if target.name == EXTENSION_NAME

  ref_path = target.product_reference&.path.to_s
  if target.name.downcase.include?('share') || ref_path == '.appex' || ref_path.empty?
    puts "Removing stale extension target: #{target.name} (#{ref_path})"
    target.remove_from_project
  end
end

# Ensure app bundle id is controlled by the Codemagic environment.
app_target.build_configurations.each do |config|
  config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = APP_BUNDLE_ID
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
  if USE_APP_GROUPS
    config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'App/App.entitlements'
  else
    config.build_settings.delete('CODE_SIGN_ENTITLEMENTS')
  end
end

unless app_target.source_build_phase.files_references.include?(pending_share_ref)
  app_target.source_build_phase.add_file_reference(pending_share_ref, true)
end
unless app_target.source_build_phase.files_references.include?(bridge_controller_ref)
  app_target.source_build_phase.add_file_reference(bridge_controller_ref, true)
end

extension_group = project.main_group.find_subpath(EXTENSION_NAME, true)
extension_group.set_source_tree('<group>')
extension_group.path = EXTENSION_NAME

source_ref = extension_group.files.find { |f| File.basename(f.path.to_s) == 'ShareViewController.swift' } || extension_group.new_file('ShareViewController.swift')
info_ref = extension_group.files.find { |f| File.basename(f.path.to_s) == 'Info.plist' } || extension_group.new_file('Info.plist')

extension_target = project.targets.find { |t| t.name == EXTENSION_NAME }
unless extension_target
  extension_target = project.new_target(:app_extension, EXTENSION_NAME, :ios, DEPLOYMENT_TARGET)
end

extension_product_name = EXTENSION_NAME
extension_product_filename = "#{EXTENSION_NAME}.appex"
extension_module_name = EXTENSION_NAME.gsub(/[^A-Za-z0-9_]/, '_')

# Xcode 26's build system is stricter about product names. If PRODUCT_NAME is
# empty, the extension archive output becomes `.appex`, which can collide with
# other build outputs and fail with: "Multiple commands produce .../.appex".
extension_target.product_reference.name = extension_product_filename
extension_target.product_reference.path = extension_product_filename
extension_target.product_reference.explicit_file_type = 'wrapper.app-extension'
extension_target.product_reference.include_in_index = '0'

extension_target.build_configurations.each do |config|
  config.build_settings['PRODUCT_NAME'] = extension_product_name
  config.build_settings['EXECUTABLE_NAME'] = '$(PRODUCT_NAME)'
  config.build_settings['WRAPPER_EXTENSION'] = 'appex'
  config.build_settings['PRODUCT_BUNDLE_PACKAGE_TYPE'] = 'XPC!'
  config.build_settings['PRODUCT_MODULE_NAME'] = extension_module_name
  config.build_settings['FULL_PRODUCT_NAME'] = '$(PRODUCT_NAME).$(WRAPPER_EXTENSION)'
  config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = EXTENSION_BUNDLE_ID
  config.build_settings['INFOPLIST_FILE'] = "#{EXTENSION_NAME}/Info.plist"
  config.build_settings['GENERATE_INFOPLIST_FILE'] = 'NO'
  config.build_settings['SWIFT_VERSION'] = '5.0'
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2'
  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
  config.build_settings['SKIP_INSTALL'] = 'YES'
  config.build_settings['DEFINES_MODULE'] = 'YES'
  config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
  config.build_settings['SDKROOT'] = 'iphoneos'
  config.build_settings['SUPPORTED_PLATFORMS'] = 'iphoneos iphonesimulator'
  config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(inherited)', '@executable_path/Frameworks', '@executable_path/../../Frameworks']
  config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
  if USE_APP_GROUPS
    config.build_settings['CODE_SIGN_ENTITLEMENTS'] = "#{EXTENSION_NAME}/#{EXTENSION_NAME}.entitlements"
  else
    config.build_settings.delete('CODE_SIGN_ENTITLEMENTS')
  end
  config.build_settings['MARKETING_VERSION'] = ENV.fetch('MARKETING_VERSION', '1.0')
  # Keep the extension build number identical to the app build for App Store validation.
  config.build_settings['CURRENT_PROJECT_VERSION'] = ENV.fetch('BUILD_NUMBER', '36')
end

# Add Swift source to extension target once.
unless extension_target.source_build_phase.files_references.include?(source_ref)
  extension_target.source_build_phase.add_file_reference(source_ref, true)
end

# Create dependency and embed the extension into the main app under PlugIns.
unless app_target.dependencies.any? { |d| d.target == extension_target }
  app_target.add_dependency(extension_target)
end

embed_phase = app_target.copy_files_build_phases.find { |p| p.name == 'Embed App Extensions' }
embed_phase ||= app_target.new_copy_files_build_phase('Embed App Extensions')
embed_phase.dst_subfolder_spec = '13' # PlugIns

# Keep the copy phase deterministic. Remove stale extension references first;
# then add exactly one product reference with the fixed .appex name.
embed_phase.files.dup.each do |build_file|
  ref = build_file.file_ref
  next unless ref

  display_name = ref.respond_to?(:display_name) ? ref.display_name.to_s : ''
  ref_path = ref.path.to_s
  ref_name = ref.name.to_s
  should_remove = [display_name, ref_path, ref_name].any? do |value|
    value == '.appex' || value == extension_product_filename || value.include?(EXTENSION_NAME) || value.include?('ShareExtension')
  end
  build_file.remove_from_project if should_remove
end

build_file = embed_phase.add_file_reference(extension_target.product_reference)
build_file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }


# Make the Capacitor WebView use our bridge subclass, otherwise the app-local
# PendingSharePlugin is compiled but never registered with the Capacitor bridge.
if File.exist?(APP_MAIN_STORYBOARD)
  storyboard = File.read(APP_MAIN_STORYBOARD)
  original_storyboard = storyboard.dup

  storyboard.gsub!(/customClass="CAPBridgeViewController"\s+customModule="Capacitor"(?:\s+customModuleProvider="target")?/, 'customClass="LinkVaultBridgeViewController" customModule="App" customModuleProvider="target"')
  storyboard.gsub!(/customClass="CAPBridgeViewController"/, 'customClass="LinkVaultBridgeViewController" customModule="App" customModuleProvider="target"')

  # Clean up accidental duplicate customModule attributes if the generated
  # storyboard format changes in a future Capacitor/Xcode release.
  storyboard.gsub!(/customModule="App"\s+customModuleProvider="target"\s+customModule="Capacitor"(?:\s+customModuleProvider="target")?/, 'customModule="App" customModuleProvider="target"')

  File.write(APP_MAIN_STORYBOARD, storyboard) if storyboard != original_storyboard
  unless storyboard.include?('LinkVaultBridgeViewController')
    warn "WARNING: Could not patch #{APP_MAIN_STORYBOARD}; PendingSharePlugin may not be registered."
  end
else
  warn "WARNING: Missing #{APP_MAIN_STORYBOARD}; PendingSharePlugin may not be registered."
end

project.save
entitlements_status = USE_APP_GROUPS ? "with App Group #{APP_GROUP_ID}" : 'without App Group entitlements'
puts "Added/updated #{EXTENSION_NAME} (#{EXTENSION_BUNDLE_ID}) #{entitlements_status}, registered PendingSharePlugin, and linkvaultq8:// + linkvault:// URL schemes."
