#!/usr/bin/env ruby
# Adds a real iOS Share Extension to the Capacitor iOS project generated by `npx cap add ios`.
# Run from repository root after `npx cap sync ios`.

require 'fileutils'
require 'open3'
require 'xcodeproj'

ROOT = File.expand_path('..', __dir__)
Dir.chdir(ROOT)

APP_BUNDLE_ID = ENV.fetch('BUNDLE_ID', 'com.linkvault.app')
EXTENSION_NAME = ENV.fetch('SHARE_EXTENSION_NAME', 'LinkVaultShareExtension')
EXTENSION_BUNDLE_ID = ENV.fetch('SHARE_EXTENSION_BUNDLE_ID', "#{APP_BUNDLE_ID}.ShareExtension")
DEPLOYMENT_TARGET = ENV.fetch('IOS_DEPLOYMENT_TARGET', '14.0')
PROJECT_PATH = 'ios/App/App.xcodeproj'
APP_INFO_PLIST = 'ios/App/App/Info.plist'
EXTENSION_DIR = "ios/App/#{EXTENSION_NAME}"

abort "Missing #{PROJECT_PATH}. Run: npx cap add ios && npx cap sync ios" unless File.exist?(PROJECT_PATH)
abort "Missing #{APP_INFO_PLIST}" unless File.exist?(APP_INFO_PLIST)

FileUtils.mkdir_p(EXTENSION_DIR)
FileUtils.cp('ios-share-extension/Info.plist', "#{EXTENSION_DIR}/Info.plist")
FileUtils.cp('ios-share-extension/ShareViewController.swift', "#{EXTENSION_DIR}/ShareViewController.swift")

# Add custom URL scheme: linkvault://share?url=...
def plistbuddy(*args)
  command = ['/usr/libexec/PlistBuddy'] + args + [APP_INFO_PLIST]
  _stdout, _stderr, _status = Open3.capture3(*command)
end
plistbuddy('-c', 'Delete :CFBundleURLTypes')
plistbuddy('-c', 'Add :CFBundleURLTypes array')
plistbuddy('-c', 'Add :CFBundleURLTypes:0 dict')
plistbuddy('-c', "Add :CFBundleURLTypes:0:CFBundleURLName string #{APP_BUNDLE_ID}")
plistbuddy('-c', 'Add :CFBundleURLTypes:0:CFBundleURLSchemes array')
plistbuddy('-c', 'Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string linkvault')

project = Xcodeproj::Project.open(PROJECT_PATH)
app_target = project.targets.find { |t| t.name == 'App' }
abort 'Could not find App target in iOS project' unless app_target

# Ensure app bundle id is controlled by the Codemagic environment.
app_target.build_configurations.each do |config|
  config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = APP_BUNDLE_ID
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
end

extension_group = project.main_group.find_subpath(EXTENSION_NAME, true)
extension_group.set_source_tree('<group>')
extension_group.path = EXTENSION_NAME

source_ref = extension_group.files.find { |f| File.basename(f.path.to_s) == 'ShareViewController.swift' } || extension_group.new_file('ShareViewController.swift')
info_ref = extension_group.files.find { |f| File.basename(f.path.to_s) == 'Info.plist' } || extension_group.new_file('Info.plist')

extension_target = project.targets.find { |t| t.name == EXTENSION_NAME }
unless extension_target
  extension_target = project.new_target(:app_extension, EXTENSION_NAME, :ios, DEPLOYMENT_TARGET)
end

extension_target.build_configurations.each do |config|
  config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = EXTENSION_BUNDLE_ID
  config.build_settings['INFOPLIST_FILE'] = "#{EXTENSION_NAME}/Info.plist"
  config.build_settings['SWIFT_VERSION'] = '5.0'
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2'
  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
  config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
  config.build_settings['MARKETING_VERSION'] = '1.0'
  config.build_settings['CURRENT_PROJECT_VERSION'] = ENV.fetch('BUILD_NUMBER', '1')
end

# Add Swift source to extension target once.
unless extension_target.source_build_phase.files_references.include?(source_ref)
  extension_target.source_build_phase.add_file_reference(source_ref, true)
end

# Create dependency and embed the extension into the main app under PlugIns.
unless app_target.dependencies.any? { |d| d.target == extension_target }
  app_target.add_dependency(extension_target)
end

embed_phase = app_target.copy_files_build_phases.find { |p| p.name == 'Embed App Extensions' }
embed_phase ||= app_target.new_copy_files_build_phase('Embed App Extensions')
embed_phase.dst_subfolder_spec = '13' # PlugIns
unless embed_phase.files_references.include?(extension_target.product_reference)
  build_file = embed_phase.add_file_reference(extension_target.product_reference)
  build_file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }
end

project.save
puts "Added/updated #{EXTENSION_NAME} (#{EXTENSION_BUNDLE_ID}) and linkvault:// URL scheme."
